### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by gabrik** [hrxi/tracing-loki#32]
Hi, first thank you for this crate.

I've noticed an issue about memory usage when I push logs to loki using this crate.

I can see that the RAM continues to grow until the process gets killed for OOM.
<img width="335" alt="Screenshot 2024-12-04 at 11 32 54" src="https://github.com/user-attachments/assets/90e11478-abba-4e52-ac99-937971dc07ef">

while when not using it I can see the RAM usage to be stable
<img width="314" alt="Screenshot 2024-12-04 at 11 33 35" src="https://github.com/user-attachments/assets/fea3b643-b504-43bb-8f4c-a2ec54de43cb">

I can see the same behaviour using the Insturment application on macOS
<img width="412" alt="Screenshot 2024-12-04 at 11 34 19" src="https://github.com/user-attachments/assets/73e9d025-d1ef-4d9a-adca-e046e132a73c">

That's how I'm configuring it:

```
match (
        get_loki_endpoint(),
        get_loki_apikey(),
        get_loki_apikey_header(),
    ) {
        (Some(loki_url), Some(apikey), Some(header)) => {
            let builder = tracing_loki::builder();

            let builder = match metadata.as_object() {
                Some(metadata) => metadata
                    .into_iter()
                    .try_fold(builder, |builder, (k, v)| match v.as_str() {
                        Some(v) => builder.label(k, v),
                        None => Ok(builder),
                    }),
                None => Ok(builder),
            }?;

            let (loki_layer, task) = builder
                .http_header(header, apikey)?
                .build_url(Url::parse(&loki_url)?)?;

            tracing_sub.with(loki_layer).init();
            tokio::spawn(task);
            return Ok(());
        }
        _ => {
            tracing::warn!("Missing one of the required header for Loki!")
        }
    };
    ``` 
    
    any suggestion?
    
    if you need the Allocations trace file I can share it.

**Comment by gabrik** [comment]
Maybe it comes from this line: https://github.com/hrxi/tracing-loki/blob/master/src/lib.rs#L513
has this queue seems just a couple of `Vec<LokiEvent>` and seems to just increase in size.

I see that here https://github.com/hrxi/tracing-loki/blob/master/src/lib.rs#L542 it should drop something, but given the memory usage it does not seem to happen

**Comment by hrxi** [comment]
Permalinks (press 'y' anywhere on GitHub):

https://github.com/hrxi/tracing-loki/blob/aa0f6dbbabbd189d61a9f6da12dcee74262a8ae2/src/lib.rs#L513

https://github.com/hrxi/tracing-loki/blob/aa0f6dbbabbd189d61a9f6da12dcee74262a8ae2/src/lib.rs#L542

Can you tell me a bit about your setup? How many log messages do you log per second? Do any logs make it to Loki?

**Comment by gabrik** [comment]
Logs do reach Loki, and there I can see as up to as 50logs per second.

btw I was digging on the code and I do not understand why the backgroud task does not send the event directly instead of pushing them into two `Vec` and start a task per HTTP request.

Seem to batch some of those logs, but as a results makes the whole architecture quite complex.

**Comment by hrxi** [comment]
> btw I was digging on the code and I do not understand why the backgroud task does not send the event directly instead of pushing them into two `Vec` and start a task per HTTP request.
> 
> Seem to batch some of those logs, but as a results makes the whole architecture quite complex.

Yes, the idea is to have at most one outgoing HTTPS request at a time, and always push all available log messages when starting a new HTTPS request.

**Comment by gabrik** [comment]
I tried to change the code to push the log line directly after the `receiver.next()` and the ram usage has reduced significatly.

From almost 100MB in 15m to 15MB in 15m and in general seems very stable.

**Comment by gabrik** [comment]
Doing some pseudo code.


```
loop {
   sleep(period);
   let events = receiver.drain();
   let http_request = make_request(events);
   http_client.send(http_request)
}
```

Still max one outstanding request, but memory should be bounded by the channel size (that should be also configurable).

**Comment by gabrik** [comment]
@hrxi I made the changes in #33 we can discuss them there.
But to me seems a nice improvement.

**Comment by ammario** [comment]
FWIW Started using this crate today and experienced similar uncontrolled memory growth. Although I haven't yet proven the connection.

**Comment by gabrik** [comment]
@ammario do you mind trying the fix I did in #33 and check if improves something also on your case?

**Comment by hrxi** [comment]
> Doing some pseudo code.
> 
> ```
> loop {
>    sleep(period);
>    let events = receiver.drain();
>    let http_request = make_request(events);
>    http_client.send(http_request)
> }
> ```

This seems to produce some (IMO) unnecessary sleeping that delays some log events even if nothing else happens. I don't quite like introducing artificial latency.

I'll take a look at your PR.

**Comment by ammario** [comment]
> @ammario do you mind trying the fix I did in #33 and check if improves something also on your case?
> 
> it is enough to add this to your `Cargo.toml`
> 
> ```toml
> [patch.crates-io]
> tracing-loki = { git = "https://github.com/gabrik/tracing-loki", branch = "fix/ram-usage" }
> ```

Been running it for a few days at some solid volumes (~10K TPM) without any issues. Thank you.

**Comment by gabrik** [comment]
@hrxi this seems indeed to solve the issue, in the PR I made anyway the period configurable, we are also using it internally for a week now.
It would be possible to get a review on the PR?

**Comment by ellutionist** [comment]
Hi @hrxi , is this mem issue has been solved now?
Regards.

**Comment by tazz4843** [comment]
This is still an issue for me using the latest versions. My codebase grows to about 13GB of memory used before being taken out by the OOM reaper. I've since reverted back to my prior loki ingest, but I can't use `console-subscriber` with that. Would it be possible to get a review on this PR? Thanks :)

**Comment by tazz4843** [comment]
I opted to simply rewrite `tracing-loki` from scratch and completely redesign its message architecture. It should now be significantly more reliable and less memory-hungry from my personal testing, although I've yet to test at significant scale. Unlike the above PR, it shouldn't drop messages if overloaded either, only doing so if the upstream Loki instance is down. I've also removed the custom future implementation from `BackgroundTask` which should also remove the spin loop on one core of the runtime all the time and save CPU (see the last messages in #24 for the manifestation of that bug).

The code is at https://codeberg.org/tazz4843/tracing-loki/, as well as on crates.io, and will need a small migration, most notably with `LokiBuilder`. Besides that it should mostly be a drop in replacement.

Hopefully this helps someone :)
